---
- name: Ensure application directory exists
  file:
    path: "{{ app_root }}"
    state: directory
    mode: '0755'

- name: Copy Laravel application files
  synchronize:
    src: "{{ playbook_dir }}/../laravel-app/"
    dest: "{{ app_root }}"
    delete: yes
    recursive: yes

- name: Install Composer dependencies
  composer:
    command: install
    working_dir: "{{ app_root }}"
    no_dev: no

- name: Set proper permissions
  file:
    path: "{{ app_root }}"
    owner: www-data
    group: www-data
    recurse: yes

- name: Set storage and bootstrap cache permissions
  file:
    path: "{{ item }}"
    mode: '0777'
    recurse: yes
  with_items:
    - "{{ app_root }}/storage"
    - "{{ app_root }}/bootstrap/cache"

- name: Copy .env file
  template:
    src: env.j2
    dest: "{{ app_root }}/.env"

- name: Generate application key
  command: php artisan key:generate
  args:
    chdir: "{{ app_root }}"
  register: key_generate
  changed_when: key_generate.rc == 0

- name: Run database migrations
  command: php artisan migrate --force
  args:
    chdir: "{{ app_root }}"
